version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - DB_HOST=Hello
      - DB_USER=Hello
      - DB_PASSWORD=Hello
      - DB_NAME=Hello
