services:
  oracle:
    container_name: oracle
    image: gvenzl/oracle-xe 
    environment:
      ORACLE_ALLOW_REMOTE: "true"  
      # ORACLE_USERNAME: "system"      
      ORACLE_PASSWORD: "oracle"      # Mật khẩu
      ORACLE_DATABASE: "VNPAY"        
    ports:
      - '1521:1521'  # Cổng mặc định của Oracle
    networks:
      - api-network
    healthcheck:
      test:
        [
          'CMD',
          'sqlplus',
          '-s',
          'system/oracle@//localhost:1521/ORCL',
          'SELECT 1 FROM DUAL;',
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    image: vnpay
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - DB_HOST=oracle  # Chỉnh sửa nếu bạn muốn sử dụng Oracle
      - DB_USER=root    # Chỉnh sửa nếu bạn muốn sử dụng Oracle
      - DB_PORT=1521
      - DB_PASSWORD=rootpassword  # Chỉnh sửa nếu bạn muốn sử dụng Oracle
      - DB_NAME=vnpay  # Chỉnh sửa nếu bạn muốn sử dụng Oracle
    depends_on:
      oracle:
        condition: service_healthy  # Đảm bảo dịch vụ oracle phải khỏe mạnh trước khi bắt đầu dịch vụ app
    networks:
      - api-network
    
networks:
  api-network: 
    driver: bridge
