services:
  oracle:
    container_name: oracle
    image: gvenzl/oracle-xe 
    environment:
      ORACLE_ALLOW_REMOTE: "true"  
      # ORACLE_USERNAME: "system"      
      ORACLE_PASSWORD: "oracle"      # Mật khẩu
      ORACLE_DATABASE: "VNPAY"        
    ports:
      - '1521:1521'  # Cổng mặc định của Oracle
    networks:
      - api-network
    healthcheck:
      test:
        [
          'CMD',
          'sqlplus',
          '-s',
          'system/oracle@//localhost:1521/ORCL',
          'SELECT 1 FROM DUAL;',
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    image: vnpay
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - DB_HOST=mysql
      - DB_USER=root 
      - DB_PORT=1521
      - DB_PASSWORD=rootpassword  
      - DB_NAME=vnpay
      - ORACLE_HOST=localhost
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=vnpay
      - ORACLE_USERNAME=system
      - ORACLE_PORT=1521 
    depends_on:
      oracle:
        condition: service_healthy 
    networks:
      - api-network
    
networks:
  api-network: 
    driver: bridge
