# version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: go
    ports:
      - '3306:3306'
    networks:
      - api-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p rootpassword',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  app:
    image: vnpay
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=vnpay
    depends_on:
      mysql:
        condition: service_healthy  # Đảm bảo dịch vụ mysql phải khỏe mạnh trước khi bắt đầu dịch vụ app

    networks:
      - api-network
    
networks:
  api-network: 
    driver: bridge
